### ISSUE TITLE
Basic Training Script

### ISSUE THREAD

**Issue by tyiannak** [tyiannak/deep_audio_features#1]

**Comment by tyiannak** [comment]
Task description @DimitrisKatsiros :
Create a script that
1) reads (a) a list of audio paths to folders list_of_dirs (b) a set of configuration parameters (e.g. short-term window size etc)
2) assumes the folder names correspond to classes
3) for each audio file it extracts the melgram (zeropad to maximum length)
4) uses (2) to extract class labels and trains a CNN and exports classification metrics (F1 etc)
5) saves CNN model to file

**Comment by DimitrisKatsiros** [comment]
Configuration parameters should be read from a python file, json file, command line or combination? Should I set some default values and then the command line to have higher priority over files or script default values?. Finally what about default values?

**Comment by tyiannak** [comment]
Lets have only the list of paths as command line arguments (argparse) for the time being.
The rest can be either hard coded and then from a config file (CNN layers, window sizes etc). 
For default values, I would try sth like: 50 mseconds (same for window and step so no overlapping), and a small CNN network such as 2 or 3 conv layers with 3x3 kernels (you can decide on that while experimenting on a basic classification task such as speech vs music)
