### ISSUE TITLE
"ValueError" in Transfer Learning script 

### ISSUE THREAD

**Issue by ageroul** [tyiannak/deep_audio_features#17]
Hi,
While running the **transfer learning script** in terminal, I get a **"ValueError"**:
`Resetting model to epoch 14.
Traceback (most recent call last):
  File "bin/transfer_learning.py", line 179, in <module>
    transfer_learning(model=modelpath, folders=folders, strategy=strategy)
  File "bin/transfer_learning.py", line 122, in transfer_learning
    best_model, train_losses, valid_losses, train_accuracy, \
ValueError: too many values to unpack (expected 6)`

What can I do?

Thanks!

**Comment by lobracost** [comment]
@ageroul Thank you for your feedback. I will handle it and let you know in the next few hours.

**Comment by lobracost** [comment]
@ageroul I probably fixed it with the https://github.com/tyiannak/deep_audio_features/commit/9e4cb861acd9b2534b2089e666ebda685b1d543c commit. Would you please run again the script and tell me if everything works fine? Since you are using this library for your work, in case of a possible future problem feel free to open new issues or contact me directly.

**Comment by ageroul** [comment]
> @ageroul I probably fixed it with the [9e4cb86](https://github.com/tyiannak/deep_audio_features/commit/9e4cb861acd9b2534b2089e666ebda685b1d543c) commit. Would you please run again the script and tell me if everything works fine? Since you are using this library for your work, in case of a possible future problem feel free to open new issues or contact me directly.

Yes, @lobracost you fixed the problem, I ran it and works fine!
![Στιγμιότυπο 2021-01-12, 2 23 26 μμ](https://user-images.githubusercontent.com/77274063/104314188-bec6b380-54e1-11eb-898e-d75e8d6165b6.png)

Thank you, I'll keep in touch since I am working with this library and I am also trying to run the scripts in Colab.
