### ISSUE TITLE
"pop up windows" in scripts

### ISSUE THREAD

**Issue by ageroul** [tyiannak/deep_audio_features#18]
Hi, 

When I execute the "training script" (and I think same happens  with the other two scripts also) it starts like this: 
![1](https://user-images.githubusercontent.com/77274063/104715472-4b19e600-572f-11eb-920d-2d7489b6257c.png)

I see the terminal window and a "pop up" window named "Figure 1". In order to proceed I **must close** the pop up window. If I don't nothing happens. So When I close it the script continues like this:
![2](https://user-images.githubusercontent.com/77274063/104715495-510fc700-572f-11eb-95c7-67d50f8d85f3.png)
 Again, I **have to close the window** to continue the execution. When I close it, the script continues as expected but:
 ![3](https://user-images.githubusercontent.com/77274063/104715865-c7142e00-572f-11eb-8179-53f83bc1abc9.png)

This time **I can't close the pop up** "Figure 1" window until the script is finished running.

So, suppose this problem is something you can reproduce is there a way to fix it?
It would be great if the Histograms could be saved as an image automatically without user interference.

Thank you very much,

**Comment by tyiannak** [comment]
resolved long ago
