### ISSUE TITLE
Basic Testing Script

### ISSUE THREAD

**Issue by tyiannak** [tyiannak/deep_audio_features#2]

**Comment by tyiannak** [comment]
Task description @DimitrisKatsiros 
1) (input) load model saved according to https://github.com/tyiannak/deep_audio_features/issues/1
2) (input) given a path to WAV file, read the file and extract its melgram (same as in https://github.com/tyiannak/deep_audio_features/issues/1), zero pad if needed (same as https://github.com/tyiannak/deep_audio_features/issues/1)
3) predict using model and melgram. 
4) return either the soft class outputs or the outputs of the last hidden layer (parameter used for that)

**Comment by DimitrisKatsiros** [comment]
@tyiannak This issue is resolved with a previous PR. Can we close the issue now ?
